# Generated by Django 3.0.3 on 2020-02-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookInfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hero',
            name='comment',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
